app_name: "nova backend"

http:
  address: :8000
  readtimeout: 10
  writetimeout: 2
  idletimeout: 10
  readheadertimeout: 4
  maxheaderbytes: 1024

observability:
  trace:
    endpoint: localhost:4317
  metric:
    endpoint:
  log:
    endpoint: localhost:4317

realtime-hub:
  goroutine:
    main: 5
    router: 10
    broker: 10

websocket:
  ping-interval: 3s
  write-wait: 5s
  pong-wait: 10s
  message-size: 512
  max-messages: 1024

redis:
  address: "localhost:6379"
  username: 
  password: 
  database: 0

postgres:
  address: "localhost:5432"
  username: "postgres"
  password: "Abx305"
  database: "Nova"
  
authentication:
  access:
    secret: "meow-meow"
    expires_in: 30000
    issuer: "neo"
    audience: "api-server"
  refresh: 
    secret: "meow-meow"
    expires_in: 7200000
    issuer: "neo"
    audience: "api-server"

seeds:
  users: "./seeds/users.json"
  posts: "./seeds/posts.json"
  comments: "./seeds/comments.json"
  clans: "./seeds/clans.json"
  channels: "./seeds/channels.json"
  stats: "./seeds/stats.json"