package common

import (
	"context"
	"errors"

	"github.com/abhinash-kml/nova/server/apperr"
	"github.com/google/uuid"
	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"go.uber.org/zap"
)

func TranslatePostgresError(err error, logger *zap.Logger) *apperr.Error {
	if err == nil {
		return nil
	}

	// 1. Isolate primary standard library and driver framework errors first
	if errors.Is(err, pgx.ErrNoRows) {
		return apperr.NotFound(err, "")
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return apperr.Internal(err, "Deadline exceeded")
	}
	if errors.Is(err, context.Canceled) {
		return apperr.Internal(err, "Context cancelled")
	}

	// 2. Evaluate driver-specific PostgreSQL SQLSTATE codes
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {

		// Log detailed telemetry internally for system debugging
		logger.Debug("[POSTGRESQL] Database engine error context details",
			zap.String("code", pgErr.Code),
			zap.String("message", pgErr.Message),
			zap.String("detail", pgErr.Detail),
		)

		switch pgErr.Code {

		// --- RESOURCE ALREADY EXISTS ---
		case pgerrcode.UniqueViolation: // "23505"
			return apperr.AlreadyExists(err, "")

		// --- CANNOT BE DELETED ---
		case pgerrcode.ForeignKeyViolation: // "23503"
			return apperr.CannotBeDeleted(err, "")

		// --- CANNOT BE CREATED ---
		case pgerrcode.NotNullViolation: // "23502"
			return apperr.CannotBeCreated(err, "")

		case pgerrcode.CheckViolation: // "23514"
			return apperr.CannotBeCreated(err, "")

		case pgerrcode.StringDataRightTruncationWarning: // "22001" (e.g. data too long for varchar column)
			return apperr.CannotBeCreated(err, "")

		case pgerrcode.NumericValueOutOfRange: // "22003"
			return apperr.CannotBeCreated(err, "")

		case pgerrcode.InvalidTextRepresentation: // "22P02" (e.g. invalid syntax for integer types)
			return apperr.CannotBeCreated(err, "")

		// --- CANNOT BE MODIFIED ---
		case pgerrcode.LockNotAvailable: // "55P03" (Immediate failure when using NOWAIT)
			return apperr.CannotBeModified(err, "")

		case pgerrcode.DeadlockDetected: // "40P01"
			return apperr.CannotBeModified(err, "")

		case pgerrcode.SerializationFailure: // "40001"
			return apperr.CannotBeModified(err, "")

		case pgerrcode.QueryCanceled: // "57014" (Fired when statement_timeout or lock_timeout hits)
			return apperr.CannotBeModified(err, "")

		// --- CRITICAL INTERNAL ERRORS (Class 42 Syntax / Class 53/57 Out of Memory/Disk) ---
		case pgerrcode.UndefinedColumn: // "42703" (Developer schema tracking bug)
			logger.Error("Database schema mismatch: missing column", zap.String("msg", pgErr.Message))
			return apperr.InfraIssue(err, "Infrastucture issue")

		case pgerrcode.UndefinedTable: // "42P01" (Developer schema tracking bug)
			logger.Error("Database schema mismatch: missing table", zap.String("msg", pgErr.Message))
			return apperr.InfraIssue(err, "Infrastucture issue")

		case pgerrcode.SyntaxError: // "42601" (Malformed query string syntax)
			logger.Error("Malformed SQL syntax generated by application", zap.String("msg", pgErr.Message))
			return apperr.InfraIssue(err, "Infrastucture issue")

		case pgerrcode.DiskFull: // "53100"
			logger.Error("PostgreSQL cluster critical: disk volume full", zap.Error(err))
			return apperr.InfraIssue(err, "Infrastucture issue")

		case pgerrcode.OutOfMemory: // "53200"
			logger.Error("PostgreSQL cluster critical: engine out of memory", zap.Error(err))
			return apperr.InfraIssue(err, "Infrastucture issue")

		case pgerrcode.TooManyConnections: // "53300"
			logger.Error("PostgreSQL connection limits saturated", zap.Error(err))
			return apperr.InfraIssue(err, "Infrastucture issue")

		case pgerrcode.ReadOnlySQLTransaction: // "25006" (Occurs during primary replica write steps on follower replicas)
			logger.Warn("Write operation rejected because targeted database node is read-only", zap.Error(err))
			return apperr.InfraIssue(err, "Infrastucture issue")
		}
	}

	// 3. Fallback catch-all for hardware loss, network disconnects, or unhandled SQLSTATE mappings
	logger.Error("Unclassified systemic database error encountered", zap.Error(err))
	return apperr.InfraIssue(err, "Unclassified issue")
}

func UserFromContext(ctx context.Context) uuid.UUID {
	value := ctx.Value("user_id")
	if value == nil {
		return uuid.Nil
	}

	userID, _ := uuid.Parse(value.(string))
	return userID
}
